DROP DATABASE IF EXISTS company_db;

CREATE DATABASE company_db;

USE company_db;

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL 
) ;

CREATE TABLE role (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30),
salary DECIMAL (10,2),
departmentId INT,
FOREIGN KEY (departmentId) REFERENCES department(id)
ON DELETE CASCADE
 ) ;

CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstName VARCHAR(100) NOT NULL,
lastName VARCHAR(100) NOT NULL,
JobRoleId INT,
FOREIGN KEY (JobRoleId)
REFERENCES jobRole(Id)
ON DELETE SET NULL,
employeeId INT,
FOREIGN KEY (employeeId)
REFERENCES employee(Id)
ON DELETE SET NULL
);